-- Generated by scripts/generate-questions.ts at 2026-10-05T00:00:00.000Z. 2 draft question(s).
-- Review EVERY question against your sources before approving. Nothing here is served until approved.
-- Run in the Supabase SQL Editor. Re-running is safe (on conflict do nothing).
begin;
-- anaphylaxis / en / AN-EPI / medication / difficulty 2 / key a
insert into public.questions (id, scenario_id, rubric_item_id, skill_tag, language, type, stem, options, correct_option_ids, explanation, difficulty, status, source)
select '5a3b1e00-0000-4000-8000-000000000001'::uuid, s.id, 'AN-EPI', 'medication', 'en', 'mcq',
       'An adult has hives, wheeze and low blood pressure after a sting. What should be given first?',
       '[{"id":"a","text":"Intramuscular epinephrine into the thigh"},{"id":"b","text":"An oral antihistamine"},{"id":"c","text":"Wait for the rash to settle"},{"id":"d","text":"A steroid, then observe"}]'::jsonb,
       '["a"]'::jsonb,
       'AN-EPI: intramuscular epinephrine is given promptly; antihistamines and steroids must not delay it.',
       2, 'draft', 'ai'
  from public.scenarios s where s.slug = 'anaphylaxis' and s.language = 'en'
on conflict (id) do nothing;

-- anaphylaxis / ko / AN-EPI / medication / difficulty 2 / key d
insert into public.questions (id, scenario_id, rubric_item_id, skill_tag, language, type, stem, options, correct_option_ids, explanation, difficulty, status, source)
select '5a3b1e00-0000-4000-8000-000000000002'::uuid, s.id, 'AN-EPI', 'medication', 'ko', 'mcq',
       '벌에 쏘인 뒤 두드러기, 쌕쌕거림, 혈압 저하가 나타난 성인에게 가장 먼저 해야 할 처치는?',
       '[{"id":"a","text":"경구 항히스타민제 투여"},{"id":"b","text":"스테로이드 투여 후 관찰"},{"id":"c","text":"발진이 가라앉을 때까지 대기"},{"id":"d","text":"대퇴 외측에 에피네프린 근육주사"}]'::jsonb,
       '["d"]'::jsonb,
       'AN-EPI: 에피네프린 근육주사를 지체 없이 시행하며, 항히스타민제나 스테로이드가 이를 늦춰서는 안 된다.',
       2, 'draft', 'ai'
  from public.scenarios s where s.slug = 'anaphylaxis' and s.language = 'ko'
on conflict (id) do nothing;

commit;

-- After review, approve only the ids you checked (and fix or delete the rest):
-- update public.questions set status = 'approved', reviewed_at = now() where status = 'draft' and id in (
--   '5a3b1e00-0000-4000-8000-000000000001',  -- anaphylaxis/en/AN-EPI
--   '5a3b1e00-0000-4000-8000-000000000002'  -- anaphylaxis/ko/AN-EPI
-- );
-- Retire a bad approved question later with: update public.questions set status = 'retired' where id = '...';
