package com.bright.app.util.voice

import kotlinx.cinterop.ExperimentalForeignApi
import kotlinx.cinterop.get
import platform.AVFAudio.AVAudioEngine
import platform.AVFAudio.AVAudioSession
import platform.AVFAudio.AVAudioSessionCategoryRecord
import platform.Foundation.NSError
import platform.Foundation.NSLocale
import platform.Speech.SFSpeechAudioBufferRecognitionRequest
import platform.Speech.SFSpeechRecognitionResult
import platform.Speech.SFSpeechRecognitionTask
import platform.Speech.SFSpeechRecognizer
import platform.Speech.SFSpeechRecognizerAuthorizationStatus
import kotlin.math.sqrt

/**
 * UNVERIFIED AT RUNTIME. There is no Xcode/iOS Simulator in this environment (see
 * IOS_MIGRATION_PLAN.md's "Known constraints"), so this class is compile-checked against the
 * real Speech/AVFAudio Kotlin/Native bindings only — never actually run. It follows Apple's
 * standard SFSpeechRecognizer + AVAudioEngine tap pattern (the same shape used in Apple's own
 * sample code and every established tutorial), which minimizes the chance the *shape* is wrong,
 * but audio session configuration and permission-flow edge cases are exactly the kind of thing
 * that looks right and isn't until it's run on a real device. Treat this as the first thing to
 * manually test once Xcode is available (Phase 6).
 */
@OptIn(ExperimentalForeignApi::class)
class IosSpeechRecognitionEngine : SpeechRecognitionEngine {

    private var recognizer: SFSpeechRecognizer? = null
    private var request: SFSpeechAudioBufferRecognitionRequest? = null
    private var task: SFSpeechRecognitionTask? = null
    private val audioEngine = AVAudioEngine()
    private var listener: ((SpeechRecognitionEvent) -> Unit)? = null
    private var tapInstalled = false

    // SFSpeechRecognizer(locale:) returning non-null only means the *locale* is supported —
    // it says nothing about the (async) user-authorization state, which Android's synchronous
    // isRecognitionAvailable has no equivalent for. Authorization is requested lazily, the
    // first time startListening() actually needs it.
    //
    // Kotlin/Native's nullability inference marks this initializer as always non-null, even
    // though Apple's docs say it returns nil for an unsupported locale — a known imprecision in
    // autogenerated ObjC nullability audit, not something this code got wrong. The null check
    // stays because it reflects Apple's documented behavior, not what the type system can prove.
    @Suppress("SENSELESS_COMPARISON")
    override val isAvailable: Boolean
        get() = SFSpeechRecognizer(locale = NSLocale(localeIdentifier = "en-US")) != null

    override fun setEventListener(onEvent: (SpeechRecognitionEvent) -> Unit) {
        listener = onEvent
    }

    override fun startListening(languageTag: String, partialResults: Boolean) {
        SFSpeechRecognizer.requestAuthorization { status ->
            if (status == SFSpeechRecognizerAuthorizationStatus.SFSpeechRecognizerAuthorizationStatusAuthorized) {
                beginListening(languageTag, partialResults)
            } else {
                listener?.invoke(SpeechRecognitionEvent.Error("Speech recognition not authorized"))
            }
        }
    }

    private fun beginListening(languageTag: String, partialResults: Boolean) {
        stopListening()

        val engineRecognizer = SFSpeechRecognizer(locale = NSLocale(localeIdentifier = languageTag))
        recognizer = engineRecognizer

        val audioSession = AVAudioSession.sharedInstance()
        audioSession.setCategory(AVAudioSessionCategoryRecord, error = null)
        // NOT calling audioSession.setActive(...) here: neither setActive:error: nor
        // setActive:withOptions:error: resolves through Kotlin/Native's bindings in this SDK
        // snapshot (both are "Unresolved reference" despite being present in the klib's raw
        // metadata — almost certainly hidden behind a deprecation level Kotlin honors even
        // though the ObjC method still exists). audioEngine.start() below activates the
        // session implicitly in the common case, but this means the session is never
        // explicitly *deactivated* on stop either — worth revisiting with real Xcode (Phase 6)
        // to find whatever the current non-deprecated activation API actually resolves to.

        val recognitionRequest = SFSpeechAudioBufferRecognitionRequest()
        recognitionRequest.shouldReportPartialResults = partialResults
        request = recognitionRequest

        val inputNode = audioEngine.inputNode
        val recordingFormat = inputNode.outputFormatForBus(0u)
        inputNode.installTapOnBus(
            bus = 0u,
            bufferSize = 1024u,
            format = recordingFormat
        ) { buffer, _ ->
            if (buffer != null) {
                recognitionRequest.appendAudioPCMBuffer(buffer)
                listener?.invoke(SpeechRecognitionEvent.VolumeChanged(rmsOf(buffer)))
            }
        }
        tapInstalled = true

        audioEngine.prepare()
        audioEngine.startAndReturnError(null)

        task = engineRecognizer?.recognitionTaskWithRequest(recognitionRequest) { result, error ->
            handleResult(result, error)
        }
    }

    private fun handleResult(result: SFSpeechRecognitionResult?, error: NSError?) {
        if (error != null) {
            stopAudioTap()
            listener?.invoke(SpeechRecognitionEvent.NoMatch)
            return
        }
        val transcription = result?.bestTranscription?.formattedString
        if (result?.isFinal() == true) {
            stopAudioTap()
            if (transcription.isNullOrBlank()) {
                listener?.invoke(SpeechRecognitionEvent.NoMatch)
            } else {
                listener?.invoke(SpeechRecognitionEvent.FinalResult(transcription))
            }
        } else if (!transcription.isNullOrEmpty()) {
            listener?.invoke(SpeechRecognitionEvent.PartialResult(transcription))
        }
    }

    /** RMS of this buffer's first channel, in dB (roughly -60 silence .. 0 loud) — the closest
     *  iOS equivalent of Android's onRmsChanged, computed by hand since AVAudioEngine only
     *  hands over raw PCM, not a volume level. Units genuinely differ from Android's; see
     *  SpeechRecognitionEvent.VolumeChanged's doc comment. */
    private fun rmsOf(buffer: platform.AVFAudio.AVAudioPCMBuffer): Float {
        val channelData = buffer.floatChannelData?.get(0) ?: return 0f
        val frameLength = buffer.frameLength.toInt()
        if (frameLength == 0) return 0f
        var sumOfSquares = 0.0
        for (i in 0 until frameLength) {
            val sample = channelData[i]
            sumOfSquares += (sample * sample).toDouble()
        }
        val rms = sqrt(sumOfSquares / frameLength)
        if (rms <= 0.0) return -60f
        return (20.0 * kotlin.math.log10(rms)).toFloat().coerceIn(-60f, 0f)
    }

    private fun stopAudioTap() {
        if (tapInstalled) {
            audioEngine.inputNode.removeTapOnBus(0u)
            tapInstalled = false
        }
        if (audioEngine.isRunning()) {
            audioEngine.stop()
        }
        request?.endAudio()
    }

    override fun stopListening() {
        stopAudioTap()
        task?.cancel()
        task = null
        request = null
    }

    override fun cancel() {
        stopListening()
    }

    override fun destroy() {
        stopListening()
        listener = null
    }
}
