// Builds seed_sim.sql from supabase/scenarios/*.json. Pure (no file access): scripts/gen-sim-seed.ts reads and
// writes the files, tests/scenarios_test.ts checks that the committed SQL is exactly what this produces.
import { RUBRIC_TAGS } from "./rubric.ts";
import { parseSimConfigOrThrow } from "./simconfig.ts";
import type { SimConfig } from "./types.ts";

interface AuthoredText {
  title: string;
  system_prompt: string;
  opening: string;
  fallback_reply: string;
  rubric: Record<string, string>;
}
export interface AuthoredScenario {
  slug: string;
  shared: Record<string, unknown>;
  rubric: { id: string; points: number; tags: string[] }[];
  i18n: { en: AuthoredText; ko: AuthoredText };
}
export interface BuiltRow {
  slug: string;
  language: "en" | "ko";
  title: string;
  system_prompt: string;
  rubric: { id: string; text: string; points: number; tags: string[] }[];
  sim: SimConfig;
}

export function buildRows(s: AuthoredScenario): BuiltRow[] {
  const ids = s.rubric.map((r) => r.id);
  if (new Set(ids).size !== ids.length) throw new Error(`${s.slug}: duplicate rubric id`);
  return (["en", "ko"] as const).map((language) => {
    const t = s.i18n[language];
    if (!t) throw new Error(`${s.slug}: missing ${language} text`);
    const textIds = Object.keys(t.rubric);
    if (textIds.length !== ids.length || !ids.every((id) => typeof t.rubric[id] === "string" && t.rubric[id].length > 0)) {
      throw new Error(`${s.slug}/${language}: rubric text must cover exactly the rubric ids`);
    }
    const rubric = s.rubric.map((r) => {
      if (!Number.isInteger(r.points) || r.points < 1) throw new Error(`${s.slug}: bad points on ${r.id}`);
      if (r.tags.length === 0 || !r.tags.every((tag) => (RUBRIC_TAGS as readonly string[]).includes(tag))) {
        throw new Error(`${s.slug}: unknown or missing tag on ${r.id}`);
      }
      return { id: r.id, text: t.rubric[r.id], points: r.points, tags: r.tags };
    });
    const sim = parseSimConfigOrThrow({ ...s.shared, opening: t.opening, fallback_reply: t.fallback_reply });
    return { slug: s.slug, language, title: t.title, system_prompt: t.system_prompt, rubric, sim };
  });
}

const Q = "$bright$"; // dollar-quote tag; the content must never contain it
const lit = (v: string) => {
  if (v.includes(Q)) throw new Error("content contains the dollar-quote tag");
  return `${Q}${v}${Q}`;
};

export function buildSql(scenarios: AuthoredScenario[]): string {
  const rows = scenarios.flatMap(buildRows);
  const values = rows.map((r) =>
    `(${lit(r.slug)}, ${lit(r.language)}, ${lit(r.title)}, ${lit(r.system_prompt)},\n` +
    ` ${lit(JSON.stringify(r.rubric))}::jsonb,\n ${lit(JSON.stringify(r.sim))}::jsonb, false)`
  ).join(",\n");
  return `-- GENERATED by scripts/gen-sim-seed.ts from supabase/scenarios/*.json. Do not edit by hand; edit the JSON and re-run.
-- NEEDS MEDICAL REVIEW BEFORE RELEASE: these scenarios are inserted INACTIVE (active = false), so users cannot see
-- or start them. Re-running this file refreshes the content but never changes \`active\`. Activate only after a
-- clinician has reviewed and signed off:  update public.scenarios set active = true where slug in (...);
-- (and update the title and sim.review.status at the same time).
insert into public.scenarios (slug, language, title, system_prompt, rubric, sim, active) values
${values}
on conflict (slug, language) do update
  set title = excluded.title,
      system_prompt = excluded.system_prompt,
      rubric = excluded.rubric,
      sim = excluded.sim;
`;
}
