export const en = {
  nav: { signIn: 'Sign in', download: 'Download', language: 'EN' },
  hero: { eyebrow: 'Emergency scenario practice', title: "Practice the emergency before it's real.", body: 'Bright is an AI patient you can talk to. Work through emergency scenarios in your own words, then see what you got right and what you missed.', download: 'Download for Android', google: 'Sign in with Google', note: 'Free to start. Just sign in.' },
  demo: { label: 'Live practice / scripted', title: 'Think out loud. Learn what to do next.', patient: "I'm having trouble breathing and feel faint.", user: 'I would check the airway, call for help, and ask when this started.', reaction: 'Okay... I can hear people coming.', score: 'Scenario score', replay: 'Replay', caption: 'Example scenario, scripted for illustration.', checklist: ['Airway checked', 'Called for help', 'Asked about allergies', 'Checked responsiveness'] },
  how: { label: '01 — How it works', title: 'A practice loop that remembers where you need work.', steps: [['01', 'Pick a scenario', 'Choose an emergency situation and meet the patient or doctor inside it.'], ['02', 'Respond in your own words', 'Type what you would do. There is no script to memorize.'], ['03', 'See what you missed', 'Get a checklist-based score and a clear next place to practice.']] },
  get: { label: '02 — The useful part', title: 'Simple tools for steady progress.', items: [['Scored against a checklist', 'See the actions you covered and the ones you missed.'], ['Streaks and history', 'Keep a record of practice, so each session has somewhere to go.'], ['A profile of your weak spots', 'Bright guides you toward the scenarios you struggle with.'], ['English and Korean', 'Practice in English or 한국어.'], ['Light and dark', 'The interface follows your phone, with a manual toggle here too.'], ['Voice input', 'Planned — not available yet.']] },
  pricing: { label: '03 — Pricing', title: 'Free to start. Paid plans are coming later.', free: 'Free', available: 'Available now', pro: 'Pro', plus: 'Plus', soon: 'Coming soon' },
  not: { label: '04 — Important', title: 'What Bright is not', body: 'Bright is a training simulation. It is not medical advice and does not replace supervised clinical training or real emergency care. The AI can make mistakes, so check against your official guidelines.' },
  faq: { label: '05 — Questions', title: 'Clear answers, no fine print.', items: [['Is it free?', 'Yes. Bright is free to start. Planned paid plans are not live yet.'], ['Do I need an account?', 'Yes. Sign in with Google so your progress and limits can be kept.'], ['Which devices?', 'Android is available now. iOS is in development.'], ['Is it a replacement for training?', 'No. Bright is a practice simulation, not supervised clinical training or real emergency care.'], ['How are my chats handled?', '[TODO: confirm real data handling before publishing, e.g. history stored on device, messages sent to an AI provider to generate replies]']] },
  footer: { privacy: '[TODO: Privacy policy link]', terms: '[TODO: Terms link]', contact: '[TODO: contact]', release: 'GitHub Releases', disclaimer: 'Training simulation only. Not medical advice.' }
} as const
export type Messages = typeof en
